### ISSUE TITLE
please add these

### ISSUE THREAD

**Issue by stewones** [esm-bundle/new-repo-instructions#15]
### Please create an esm-bundle repo for the following package(s):

- https://www.npmjs.com/package/@rebased/angular
- https://www.npmjs.com/package/@rebased/cache
- https://www.npmjs.com/package/@rebased/core
- https://www.npmjs.com/package/@rebased/firebase
- https://www.npmjs.com/package/@rebased/parse
- https://www.npmjs.com/package/@rebased/state

### Steps for esm-bundle maintainer

The maintainers of esm-bundle will do the following:

1. Create a repo from this template. Click on "Use Template". The new repo must be under the `esm-bundle` repo https://github.com/esm-bundle/autopublish-template
2. Create branch protection rule for the `main` branch. Code reviews are required by a code owner before merge, and the `build` github workflow must succeed before merge.

### Steps for new contributor

Once the maintainer has created the repository, fork it and follow these steps: https://github.com/esm-bundle/new-repo-instructions#okay-how-do-i-do-it. Once finished, submit a pull request, which will be reviewed by the maintainers.

**Comment by internettrans** [comment]
Repos created at the following links. Please @ me when creating pull requests, as a I snooze notifications since there are so many dependency upgrade PRs for esm-bundle repos.

https://github.com/esm-bundle/rebased__angular
https://github.com/esm-bundle/rebased__cache
https://github.com/esm-bundle/rebased__core
https://github.com/esm-bundle/rebased__firebase
https://github.com/esm-bundle/rebased__parse
https://github.com/esm-bundle/rebased__state

**Comment by stewones** [comment]
esm-bundle project is really awesome @joeldenning thank you.
I'll do PRs asap.
