### ISSUE TITLE
esm-bundle/antd

### ISSUE THREAD

**Issue by RebecaLozrey** [esm-bundle/new-repo-instructions#17]
### Please create an esm-bundle repo for the following package(s):

-https://www.npmjs.com/package/antd

### Steps for esm-bundle maintainer

The maintainers of esm-bundle will do the following:

1. Create a repo from this template. Click on "Use Template". The new repo must be under the `esm-bundle` repo https://github.com/esm-bundle/autopublish-template
2. Create branch protection rule for the `main` branch. Code reviews are required by a code owner before merge, and the `build` github workflow must succeed before merge.

### Steps for new contributor

Once the maintainer has created the repository, fork it and follow these steps: https://github.com/esm-bundle/new-repo-instructions#okay-how-do-i-do-it. Once finished, submit a pull request, which will be reviewed by the maintainers.

**Comment by RebecaLozrey** [comment]
@joeldenning @TheMcMurder Hi!
To comply with this, I need something from you right?
Make sure to create the new repo under the esm-bundle organization instead of your personal Github
![image](https://user-images.githubusercontent.com/906082/119551217-fe8a8b00-bd5e-11eb-8e42-7519ba516f2a.png)
Could you create the template under esm-bundle/ ownership?

**Comment by RebecaLozrey** [comment]
This is where all components are exported:
https://github.com/ant-design/ant-design/blob/master/components/index.tsx
How does this should look like in package.json?
![image](https://user-images.githubusercontent.com/906082/119554115-ed8f4900-bd61-11eb-854e-5f988dea8d60.png)
*main and module properties

**Comment by RebecaLozrey** [comment]
Do you recomend that I export each UI component independenty, if so, How can I do it?
![image](https://user-images.githubusercontent.com/906082/119563844-b0c94f00-bd6d-11eb-92b2-9aea69bce2bb.png)

**Comment by internettrans** [comment]
The repo should be under the esm-bundle organization. I've created it at https://github.com/esm-bundle/antd.

> This is where all components are exported:
> https://github.com/ant-design/ant-design/blob/master/components/index.tsx
> How does this should look like in package.json?

The rollup config's `input` is what determines which files are bundled. You can usually just specify the package name (`antd`) as the rollup `input`, and it'll work because it looks at antd's `main` and `exports` fields in its package.json. You can also specify `antd/subfolder/file.js` to use a specific file. Another thing to note is that the src files are not published to npm, only the bundle. See https://www.jsdelivr.com/package/npm/antd which shows the files that are published to npm - only those are available for rebundling.

> Do you recomend that I export each UI component independenty, if so, How can I do it?

With in-browser modules, each file corresponds to an import. So if you do `import { Button } from 'antd'`, then you only need one bundle. But if need to do `import Button from 'antd/Button'` and `import Breadcrumb from 'antd/Breadcrumb'`, then you need separate bundles for each
