### ISSUE TITLE
Repo access

### ISSUE THREAD

**Issue by dlecan** [esm-bundle/new-repo-instructions#8]
### My username on npmjs.com

My username on npmjs.com is dlecan

### I will create an esm-bundle repo for the following npm packages:
- https://www.npmjs.com/package/bcrypto

### I am not an evil charlatan
- [x] I will use my permissions within the esm-bundle Github organization to further the greater community's interests.
I will transfert these permissions to the upstream if they wish, and I hope this bundle will be transient.
I would like the original bundle supports esm in the future.

**Comment by joeldenning** [comment]
Welcome @dlecan - I've given you access on Github to create repos and on npm to publish `@esm-bundle/bcrypto`. I published version 0.0.0 of the package so that I could give you access to that package. You can see it at https://www.npmjs.com/package/@esm-bundle/bcrypto. I ran into some weird things with the npm CLI so I ended up giving you publish access via the npm UI, which in my experience hasn't always done what I thought it would. Let me know if you run into any issues
